---

  - name: Add a new tenant
    aci_tenant:
      host: apic1
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.name }}"
      description: "{{ item.description }}"
      state: present
    with_items: "{{ tenants }}"

  - name: Add a new ANP to Tenant
    aci_ap:
      host: apic1
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.tenant }}"
      ap: "{{ item.name }}"
      description: "{{ item.description }}"
      state: present
    with_items: "{{ anps }}"

  - name: Add a new bd
    aci_bd:
      host: apic1
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.tenant }}"
      bd: "{{ item.name }}"
      description: "{{ item.description }}"
      vrf: "{{ item.vrf }}"
      state: present
    with_items: "{{ bds }}"

  - name: create a subnet with options
    aci_bd_subnet:
      host: apic1
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.tenant }}"
      bd: "{{ item.name }}"
      subnet_name: "{{ item.subnet_name }}"
      gateway: "{{ item.gw }}"
      mask: "{{ item.mask }}"
      scope: "{{ item.scope }}"
    with_items: "{{ bds }}"

  - name: associate a bd to an existing l3out
    aci_bd_to_l3out:
      host: apic1
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.tenant }}"
      bd: "{{ item.name }}"
      l3out: "{{ item.l3out }}"
    with_items: "{{ bds }}"
    when: "'WEB-TIER' in item.name" 

  - name: Add a new epg
    aci_epg:
      host: apic1
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.tenant }}"
      ap: "{{ item.ap }}"
      epg: "{{ item.name }}"
      description: "{{ item.description }}"
      bd: "{{ item.bd }}"
      state: present
    with_items: "{{ epg }}"

  - name: Add a new domain to EPG binding
    aci_epg_to_domain:
      host: apic1
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.tenant }}"
      ap: "{{ item.ap }}"
      epg: "{{ item.name }}"
      domain: "{{ item.domain }}"
      domain_type: "{{ item.domain_type }}"
      vm_provider: "{{ item.vm_provider }}"
      state: present
    with_items: "{{ epg }}"

  - name: Add a new contract for EPG to EPG Communication
    aci_epg_to_contract:
      host: apic1
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.tenant }}"
      ap: "{{ item.ap }}"
      epg: "{{ item.epg }}"
      contract: "{{ item.name }}"
      contract_type: "{{ item.type }}"
      state: present
    with_items: "{{ epg_contracts }}"


  - name: Add a new contract for EPG to L3OUT Communication
    aci_epg_to_contract:
      host: apic1
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
      tenant: "{{ item.tenant }}"
      ap: "{{ item.ap }}"
      epg: "{{ item.epg }}"
      contract: "{{ item.name }}"
      contract_type: "{{ item.type }}"
      state: present
    with_items: "{{ l3out_contracts }}"
